- name: rand-user-agent
  title: rand-user-agent Package Hijacked With RAT
  repo: https://github.com/WebScrapingAPI/rand-user-agent
  synopsis: Attackers compromised the NPM account of the maintainer and published malicious versions of the rand-user-agent package. The compromised versions contained obfuscated code that installed a Remote Access Trojan (RAT), which established a connection to a command-and-control server. The malware could execute arbitrary commands, upload files from victims' machines, and modify the PATH environment variable to hijack Python execution.
  start_date: 2025-05-05
  end_date: 2025-05-05
  attribution_type: Individual Hacker
  component_type: Library
  lang: JavaScript
  cause: Compromised Account/Credentials
  motive: Unauthorized Access/Control
  transitive: false
  insertion_phase: distribution
  impact_type: Backdoor/Remote Code Execution
  impact_user_count: 45000
  references:
    - https://www.aikido.dev/blog/catching-a-rat-remote-access-trojian-rand-user-agent-supply-chain-compromise
    - https://www.npmjs.com/package/rand-user-agent
  versions:
    - 1.0.110
    - 2.0.83
    - 2.0.84
  historical_artifacts:
    - https://registry.npmjs.org/rand-user-agent/-/rand-user-agent-1.0.110.tgz
    - https://registry.npmjs.org/rand-user-agent/-/rand-user-agent-2.0.83.tgz
    - https://registry.npmjs.org/rand-user-agent/-/rand-user-agent-2.0.84.tgz
  current_artifacts:
    - https://www.aikido.dev/blog/catching-a-rat-remote-access-trojian-rand-user-agent-supply-chain-compromise
  domain: npmjs.org
  domain_type: package host
  artifact_type: source archive
  hashes:
    - sha256:4ecdf8ceee1f2345ef9996c15f44eee3f87a1e04baa0fb0f91cc228e699a2873
